
import java.util.ArrayList;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lydia
 */
public class Customer extends javax.swing.JFrame {
   ArrayList<CustomerDetails> customers = RetrieveCustomer.readFile("customer.txt");
    CustomerDetails cusDetails;
    /**
     * Creates new form Customer
     */
     private void initiateCustomers(){
   
    for (CustomerDetails c: customers){
        CboFullName.addItem(c);
    }
    }

    
    public Customer() {
        initComponents();
        initiateCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        CboFullName = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ICNumber = new javax.swing.JTextField();
        AccountType = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AccBalance = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        AccNumber = new javax.swing.JTextField();
        CusID = new javax.swing.JTextField();
        Gender = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Race = new javax.swing.JTextField();
        ContactNumber = new javax.swing.JTextField();
        Edit = new javax.swing.JButton();
        Save = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 0, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bank.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 150));

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CUSTOMER PROFILE");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 67, 310, 39));

        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        Search.setBackground(new java.awt.Color(0, 0, 153));
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        Search.setBorderPainted(false);
        Search.setContentAreaFilled(false);
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel4.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 35, -1));

        Back.setBackground(new java.awt.Color(204, 204, 255));
        Back.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("BACK");
        Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back.setContentAreaFilled(false);
        Back.setOpaque(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel4.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 60, 30));

        CboFullName.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        CboFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboFullNameActionPerformed(evt);
            }
        });
        jPanel4.add(CboFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 170, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 160));

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel5.setText("CustomerID:");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel6.setText("Account Type:");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel7.setText("Contact Number:");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        ICNumber.setEditable(false);
        ICNumber.setBackground(new java.awt.Color(204, 204, 255));
        ICNumber.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        ICNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel8.add(ICNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 173, 32));

        AccountType.setEditable(false);
        AccountType.setBackground(new java.awt.Color(204, 204, 255));
        AccountType.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        AccountType.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel8.add(AccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 173, 32));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel8.setText("RM");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        AccBalance.setEditable(false);
        AccBalance.setBackground(new java.awt.Color(204, 204, 255));
        AccBalance.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        AccBalance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        AccBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccBalanceActionPerformed(evt);
            }
        });
        jPanel8.add(AccBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 145, 32));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel9.setText("Balance:");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 20));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel10.setText("IC No/Passprt:");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel11.setText("Gender:");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel12.setText("Address:");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel13.setText("Race:");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel14.setText("Account Number:");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        AccNumber.setEditable(false);
        AccNumber.setBackground(new java.awt.Color(204, 204, 255));
        AccNumber.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        AccNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel8.add(AccNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 173, 32));

        CusID.setEditable(false);
        CusID.setBackground(new java.awt.Color(204, 204, 255));
        CusID.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        CusID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel8.add(CusID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 173, 32));

        Gender.setEditable(false);
        Gender.setBackground(new java.awt.Color(204, 204, 255));
        Gender.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Gender.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel8.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 173, 32));

        Address.setEditable(false);
        Address.setBackground(new java.awt.Color(204, 204, 255));
        Address.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Address.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddressMouseClicked(evt);
            }
        });
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });
        Address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AddressKeyPressed(evt);
            }
        });
        jPanel8.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 173, 32));

        Race.setEditable(false);
        Race.setBackground(new java.awt.Color(204, 204, 255));
        Race.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Race.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel8.add(Race, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 173, 32));

        ContactNumber.setEditable(false);
        ContactNumber.setBackground(new java.awt.Color(204, 204, 255));
        ContactNumber.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        ContactNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ContactNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContactNumberKeyPressed(evt);
            }
        });
        jPanel8.add(ContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 173, 32));

        Edit.setBackground(new java.awt.Color(153, 153, 255));
        Edit.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        Edit.setIcon(new javax.swing.ImageIcon("C:\\Users\\lydia\\Documents\\NetBeansProjects\\Banking_System\\src\\Images\\edit_file_26px.png")); // NOI18N
        Edit.setText("Edit");
        Edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Edit.setContentAreaFilled(false);
        Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel8.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 90, 40));

        Save.setBackground(new java.awt.Color(153, 153, 255));
        Save.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        Save.setIcon(new javax.swing.ImageIcon("C:\\Users\\lydia\\Documents\\NetBeansProjects\\Banking_System\\src\\Images\\save_close.png")); // NOI18N
        Save.setText("Save");
        Save.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Save.setContentAreaFilled(false);
        Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Save.setOpaque(false);
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel8.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 90, 40));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 820, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SearchActionPerformed

    private void AccBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccBalanceActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Only Address and Contact Number are allowed to edit!");
        Address.setEditable(true);
        ContactNumber.setEditable(true);
    }//GEN-LAST:event_EditActionPerformed

    private void CboFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboFullNameActionPerformed
        // TODO add your handling code here:

        cusDetails =  (CustomerDetails) CboFullName.getSelectedItem();
        CusID.setText(cusDetails.getCusID());
        AccNumber.setText(cusDetails.getAccNumber());
        AccountType.setText(cusDetails.getAccountType());
        AccBalance.setText(String.valueOf(cusDetails.getAccBalance()));
        ICNumber.setText(cusDetails.getICNumber());
        Gender.setText(cusDetails.getGender());
        Address.setText(cusDetails.getAddress());
        Race.setText(cusDetails.getRace());
        ContactNumber.setText(cusDetails.getContactNumber());
        
      
    }//GEN-LAST:event_CboFullNameActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
       RetrieveCustomer.writeFile(customers, "customer.txt");
       JOptionPane.showMessageDialog(this, "Address has been updated!");
       Address.setEditable(false);
       ContactNumber.setEditable(false);
    }//GEN-LAST:event_SaveActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        dispose();
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void AddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddressKeyPressed
        // TODO add your handling code here:
      String updateAddString = JOptionPane.showInputDialog(this, "Enter New Address:", "Update Address", JOptionPane.PLAIN_MESSAGE);
      String updateAdd = updateAddString;
      cusDetails.update(updateAdd);
      Address.setText(String.valueOf(cusDetails.getAddress()));
    }//GEN-LAST:event_AddressKeyPressed

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
                                      
    }//GEN-LAST:event_AddressActionPerformed

    private void AddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddressMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressMouseClicked

    private void ContactNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactNumberKeyPressed
        // TODO add your handling code here:
       String updateContactString = JOptionPane.showInputDialog(this, "Enter New Contact Number:", "Update Address", JOptionPane.PLAIN_MESSAGE);
       String updateContact = updateContactString;
       cusDetails.contact(updateContact);
       ContactNumber.setText(String.valueOf(cusDetails.getContactNumber()));
    }//GEN-LAST:event_ContactNumberKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
      
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccBalance;
    private javax.swing.JTextField AccNumber;
    private javax.swing.JTextField AccountType;
    private javax.swing.JTextField Address;
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<CustomerDetails> CboFullName;
    private javax.swing.JTextField ContactNumber;
    private javax.swing.JTextField CusID;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField ICNumber;
    private javax.swing.JTextField Race;
    private javax.swing.JButton Save;
    private javax.swing.JButton Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
