
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lydia
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
           
      Welcomelbl.setText(String.valueOf("Welcome" + " " + PassUsername.getTxtUsername() + "!"));

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jBtnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Welcomelbl = new javax.swing.JLabel();
        jBtnLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CustomerDetails = new javax.swing.JButton();
        CreateAcc = new javax.swing.JButton();
        DepositMoney = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jBtnBack.setBackground(new java.awt.Color(0, 0, 153));
        jBtnBack.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jBtnBack.setForeground(new java.awt.Color(255, 255, 255));
        jBtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go_back.png"))); // NOI18N
        jBtnBack.setText("Back To Dashboard");
        jBtnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnBack.setBorderPainted(false);
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Welcomelbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        Welcomelbl.setForeground(new java.awt.Color(255, 255, 255));
        Welcomelbl.setText("WELCOME");
        jPanel1.add(Welcomelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jBtnLogout.setBackground(new java.awt.Color(0, 0, 153));
        jBtnLogout.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jBtnLogout.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go_back.png"))); // NOI18N
        jBtnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnLogout.setBorderPainted(false);
        jBtnLogout.setContentAreaFilled(false);
        jBtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 43));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 100));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CustomerDetails.setBackground(new java.awt.Color(204, 204, 255));
        CustomerDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create_96px.png"))); // NOI18N
        CustomerDetails.setBorderPainted(false);
        CustomerDetails.setContentAreaFilled(false);
        CustomerDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CustomerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(CustomerDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 120, 100));

        CreateAcc.setBackground(new java.awt.Color(204, 204, 255));
        CreateAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adduser.png"))); // NOI18N
        CreateAcc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        CreateAcc.setBorderPainted(false);
        CreateAcc.setContentAreaFilled(false);
        CreateAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccActionPerformed(evt);
            }
        });
        jPanel2.add(CreateAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 120, 100));

        DepositMoney.setBackground(new java.awt.Color(204, 204, 255));
        DepositMoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/money_bag.png"))); // NOI18N
        DepositMoney.setBorderPainted(false);
        DepositMoney.setContentAreaFilled(false);
        DepositMoney.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DepositMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositMoneyActionPerformed(evt);
            }
        });
        jPanel2.add(DepositMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 139, 111));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel2.setText("Edit Customer Details");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel3.setText("Create Account");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel5.setText("Deposit/Withdraw Money");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 670, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerDetailsActionPerformed
        // TODO add your handling code here:
        dispose();
        Customer Cus = new Customer();
        Cus.setVisible(true);
    }//GEN-LAST:event_CustomerDetailsActionPerformed

    private void CreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccActionPerformed
        // TODO add your handling code here:
        dispose();
        CreateAccount CreateAccount = new CreateAccount();
        CreateAccount.setVisible(true);
        
        CreateAcc.setOpaque(false);
        CreateAcc.setContentAreaFilled(false);
        CreateAcc.setBorderPainted(false);
       
    
    }//GEN-LAST:event_CreateAccActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login Login = new Login();
        Login.setVisible(true);
    }//GEN-LAST:event_jBtnLogoutActionPerformed

    private void DepositMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositMoneyActionPerformed
        // TODO add your handling code here:
        dispose();
        Deposit Deposit = new Deposit();
        Deposit.setVisible(true);
    }//GEN-LAST:event_DepositMoneyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAcc;
    private javax.swing.JButton CustomerDetails;
    private javax.swing.JButton DepositMoney;
    private javax.swing.JLabel Welcomelbl;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnLogout;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
