import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lydia
 */
public class Deposit extends javax.swing.JFrame {
    ArrayList<Account> accounts = Retrieve.readFile("customer.txt");
    Account currentAccount;
    
    private void initiateAccounts(){
   
    for (Account a: accounts){
        CboAccNum.addItem(a);
    }
    }
    /**
     * Creates new form Deposit
     */
    public Deposit() {
        initComponents();
        initiateAccounts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerName3 = new javax.swing.JTextField();
        CustomerName4 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ICNo = new javax.swing.JTextField();
        AccType = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Balance = new javax.swing.JTextField();
        DepositBtn = new javax.swing.JButton();
        WithdrawBtn = new javax.swing.JButton();
        TransferBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        AccName = new javax.swing.JTextField();
        CustomerID = new javax.swing.JTextField();
        Gender = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Race = new javax.swing.JTextField();
        ContactNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CboAccNum = new javax.swing.JComboBox<>();
        BtnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        CustomerName3.setEditable(false);
        CustomerName3.setBackground(new java.awt.Color(204, 204, 255));
        CustomerName3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        CustomerName4.setEditable(false);
        CustomerName4.setBackground(new java.awt.Color(204, 204, 255));
        CustomerName4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 0, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("L-BANKING.");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 190, 39));

        BackBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go_back.png"))); // NOI18N
        BackBtn.setBorderPainted(false);
        BackBtn.setContentAreaFilled(false);
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel4.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel5.setText("CustomerID:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel6.setText("Account Type:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel7.setText("Contact Number:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        ICNo.setEditable(false);
        ICNo.setBackground(new java.awt.Color(204, 204, 255));
        ICNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ICNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(ICNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 173, 32));

        AccType.setEditable(false);
        AccType.setBackground(new java.awt.Color(204, 204, 255));
        AccType.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AccType.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(AccType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 173, 32));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel8.setText("RM");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        Balance.setEditable(false);
        Balance.setBackground(new java.awt.Color(204, 204, 255));
        Balance.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Balance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceActionPerformed(evt);
            }
        });
        jPanel2.add(Balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 145, 32));

        DepositBtn.setBackground(new java.awt.Color(153, 153, 255));
        DepositBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        DepositBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/deposit_16px.png"))); // NOI18N
        DepositBtn.setText("Deposit");
        DepositBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DepositBtn.setContentAreaFilled(false);
        DepositBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DepositBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositBtnActionPerformed(evt);
            }
        });
        jPanel2.add(DepositBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 100, 40));

        WithdrawBtn.setBackground(new java.awt.Color(153, 153, 255));
        WithdrawBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        WithdrawBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/withdrawal_limit_16px.png"))); // NOI18N
        WithdrawBtn.setText("Withdraw");
        WithdrawBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        WithdrawBtn.setContentAreaFilled(false);
        WithdrawBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        WithdrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawBtnActionPerformed(evt);
            }
        });
        jPanel2.add(WithdrawBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 100, 40));

        TransferBtn.setBackground(new java.awt.Color(153, 153, 255));
        TransferBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        TransferBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/card_exchange_24px.png"))); // NOI18N
        TransferBtn.setText("Transfer");
        TransferBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TransferBtn.setContentAreaFilled(false);
        TransferBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TransferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferBtnActionPerformed(evt);
            }
        });
        jPanel2.add(TransferBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 100, 40));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel9.setText("Balance:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 20));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel10.setText("IC No/Passprt:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel11.setText("Gender:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel12.setText("Address:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel13.setText("Race:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel14.setText("Name:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        AccName.setEditable(false);
        AccName.setBackground(new java.awt.Color(204, 204, 255));
        AccName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AccName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(AccName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 173, 32));

        CustomerID.setEditable(false);
        CustomerID.setBackground(new java.awt.Color(204, 204, 255));
        CustomerID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CustomerID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(CustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 173, 32));

        Gender.setEditable(false);
        Gender.setBackground(new java.awt.Color(204, 204, 255));
        Gender.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Gender.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 173, 32));

        Address.setEditable(false);
        Address.setBackground(new java.awt.Color(204, 204, 255));
        Address.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Address.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 173, 32));

        Race.setEditable(false);
        Race.setBackground(new java.awt.Color(204, 204, 255));
        Race.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Race.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(Race, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 173, 32));

        ContactNo.setEditable(false);
        ContactNo.setBackground(new java.awt.Color(204, 204, 255));
        ContactNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ContactNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(ContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 173, 32));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 810, 400));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ACCOUNT NO:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        CboAccNum.setBackground(new java.awt.Color(204, 204, 255));
        CboAccNum.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CboAccNum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CboAccNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboAccNumActionPerformed(evt);
            }
        });
        jPanel4.add(CboAccNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 160, 29));

        BtnSearch.setBackground(new java.awt.Color(204, 204, 255));
        BtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        BtnSearch.setBorderPainted(false);
        BtnSearch.setContentAreaFilled(false);
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });
        jPanel4.add(BtnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 35, -1));
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_BtnSearchActionPerformed

    private void CboAccNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboAccNumActionPerformed
        // TODO add your handling code here:
        currentAccount =  (Account) CboAccNum.getSelectedItem();
        CustomerID.setText(currentAccount.getCustomerID());
        AccName.setText(currentAccount.getAccName());
        AccType.setText(currentAccount.getAccType());
        Balance.setText(String.valueOf(currentAccount.getAccBal()));
        ICNo.setText(currentAccount.getICNo());
        Gender.setText(currentAccount.getGender());
        Address.setText(currentAccount.getAddress());
        Race.setText(currentAccount.getRace());
        ContactNo.setText(currentAccount.getContactNo());
        
    }//GEN-LAST:event_CboAccNumActionPerformed

    private void BalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceActionPerformed

    private void DepositBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositBtnActionPerformed
        // TODO add your handling code here:
       String amountString = JOptionPane.showInputDialog(this, "Enter an amount to deposit:", "Deposit", JOptionPane.PLAIN_MESSAGE);
       double amount = Double.parseDouble(amountString);
       currentAccount.deposit(amount);
       Balance.setText(String.valueOf(currentAccount.getAccBal()));
       Retrieve.writeFile(accounts, "customer.txt");
       JOptionPane.showMessageDialog(this, "Money has been deposited!");
    }//GEN-LAST:event_DepositBtnActionPerformed

    private void WithdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawBtnActionPerformed
        // TODO add your handling code here:
       String amountString = JOptionPane.showInputDialog(this, "Enter an amount to withdraw:", "Withdraw", JOptionPane.PLAIN_MESSAGE);
       double amount = Double.parseDouble(amountString);
       currentAccount.withdraw(amount);
       Balance.setText(String.valueOf(currentAccount.getAccBal()));
       Retrieve.writeFile(accounts, "customer.txt");
    }//GEN-LAST:event_WithdrawBtnActionPerformed

    private void TransferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferBtnActionPerformed
        // TODO add your handling code here:
       String AccNum = JOptionPane.showInputDialog(this, "Enter account number to transfer:", "Transfer", JOptionPane.PLAIN_MESSAGE);
       Account TransferAcc = null;
       for(Account a : accounts){
           if(a.toString().equals(AccNum)){
               TransferAcc = a;
               break;
           }
       } 
       String amountString = JOptionPane.showInputDialog(this, "Enter an amount to transfer:", "Transfer", JOptionPane.PLAIN_MESSAGE);
       double amount = Double.parseDouble(amountString);
       if(TransferAcc !=null){
       currentAccount.transfer(TransferAcc, amount);
       Balance.setText(String.valueOf(currentAccount.getAccBal()));
       Retrieve.writeFile(accounts, "customer.txt");
       
       }else {
            JOptionPane.showMessageDialog(this, "Wrong Account Number! Please enter the correct Account Number!","Error", JOptionPane.ERROR_MESSAGE);

       }
    }//GEN-LAST:event_TransferBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccName;
    public javax.swing.JTextField AccType;
    private javax.swing.JTextField Address;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField Balance;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JComboBox<Account> CboAccNum;
    private javax.swing.JTextField ContactNo;
    private javax.swing.JTextField CustomerID;
    private javax.swing.JTextField CustomerName3;
    private javax.swing.JTextField CustomerName4;
    private javax.swing.JButton DepositBtn;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField ICNo;
    private javax.swing.JTextField Race;
    private javax.swing.JButton TransferBtn;
    private javax.swing.JButton WithdrawBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
